# Generated by Django 3.0.4 on 2020-09-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=100, verbose_name='move')),
                ('move_input', models.CharField(max_length=50, verbose_name='input')),
                ('move_type', models.CharField(max_length=50, verbose_name='type')),
                ('damage', models.CharField(max_length=10, verbose_name='damage')),
                ('block_damage', models.CharField(max_length=10, verbose_name='block damage')),
                ('f_block_damage', models.CharField(max_length=10, verbose_name='flawless block damage')),
                ('startup', models.CharField(max_length=10, verbose_name='startup')),
                ('Active', models.CharField(max_length=10, verbose_name='active')),
                ('Recovery', models.CharField(max_length=10, verbose_name='recovery')),
                ('cancel_adv', models.CharField(max_length=10, verbose_name='cancel advantage')),
                ('hit_adv', models.CharField(max_length=10, verbose_name='hit advantage')),
                ('block_adv', models.CharField(max_length=10, verbose_name='block advantage')),
                ('f_block_adv', models.CharField(max_length=10, verbose_name='flawless block advantage')),
                ('info', models.CharField(blank=True, max_length=250, verbose_name='information')),
                ('equip', models.CharField(blank=True, max_length=250, verbose_name='equiped move')),
                ('classification', models.CharField(max_length=50, verbose_name='move classification')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charviewer.Character')),
            ],
        ),
    ]
