# Generated by Django 3.0.4 on 2020-11-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charviewer', '0004_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
